### ISSUE TITLE
Unable to compile on Xcode 4.6.3

### ISSUE THREAD

**Issue by frantic0** [marsyas/marsyas#17]
Hello, 

I'm trying to compile Marsyas for Xcode and demo applications and I am finding errors in different situations. If I compile manually everything is fine, so I expect that there is something wrong with the configuration. 

If I configure cmake with Marsyas_Static flag DISABLED, I get linker mach-o (ld) errors, and libtool finds problems with some of the flags (-dynamic, -Wl,-headerpad_max_install_names), and Marsyas lib is only compiled by removing those flags

If I configure cmake with Marsyas_Static flag ENABLED, I compile without errors.

However, none of the examples gets compiled for any of both configurations. Has someone identified this problem yet? 

Thank you,
FB

**Comment by vedant738** [comment]
hiiiiiiiiiiiii i am working with cmake and while cconfiguring it is giving error :projects files may be invalid .
please tell me solution for this problem asap.
