### ISSUE TITLE
Problem with FindFreetype.cmake when WITH_PNG is enabled

### ISSUE THREAD

**Issue by jklepp-tgm** [marsyas/marsyas#42]
When I enable WITH_PNG with this command line:
```
cmake -DWITH_PNG=1 ../marsyas-version-0.5.0-beta1/
```
CMake is not able to complete the configuration process.

I get the following error message:
```
CMake Error at /usr/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Freetype (missing: FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake-modules/FindFreetype.cmake:92 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake-modules/marsyas-detect.cmake:124 (find_package)
  src/CMakeLists.txt:61 (include)


-- Configuring incomplete, errors occurred!
See also "/home/jakob/build/marsyas/build/CMakeFiles/CMakeOutput.log".
See also "/home/jakob/build/marsyas/build/CMakeFiles/CMakeError.log".
```
CMakeOutput.log and CMakeError.log do not contain relevant information.

The problem is caused by the block starting at line 57 in the file [cmake-modules/FindFreetype.cmake](https://github.com/marsyas/marsyas/blob/master/cmake-modules/FindFreetype.cmake).
Freetype2 is installed on my system but there is no path matching ``freetype/config/ftheader.h``.

Replacing marsyas FindFreetype.cmake with [a newer version](https://github.com/Kitware/CMake/blob/master/Modules/FindFreetype.cmake) fixed this problem for me.

**Comment by jleben** [comment]
Thanks! I fixed it by simply removing our FindFreetype.cmake, which will result in automatically using the one that's already provided by CMake.
