### ISSUE TITLE
Error in make install

### ISSUE THREAD

**Issue by relliottsmith** [marsyas/marsyas#46]
Hey,
When running make install I get this error. 

    -- Installing: /Library/Python/2.7/site-packages/libmarsyas.dylib
    CMake Error at src/marsyas/cmake_install.cmake:171 (file):
      file INSTALL cannot copy file
      "/Users/rees/marsyas/build/lib/libmarsyas.dylib" to
      "/Library/Python/2.7/site-packages/libmarsyas.dylib".
    Call Stack (most recent call first):
      src/cmake_install.cmake:33 (include)
      cmake_install.cmake:32 (include)

**Comment by jleben** [comment]
Try "sudo make install".

**Comment by relliottsmith** [comment]
Ah, yeah, sorry. That works.
