### ISSUE TITLE
Audio input from rtsp

### ISSUE THREAD

**Issue by juanbraga** [marsyas/marsyas#52]
Congrats for your library! It's a great contribution!

I am just curious about audio input from rtsp streaming for real time audio analysis. 

I could not find anything about that right away, so I want to know if there is any audio I/O function that supports rtsp or would need some extra implementation?

Thanks in advance!

**Comment by xiaolongDGitHub** [comment]
hi,Do you know how to load my data to the stream   eg :a double *array, and how to get the result stream to a array?
