### ISSUE TITLE
Wrong dir for CMake

### ISSUE THREAD

**Issue by ybayle** [marsyas/marsyas#62]
I get the following message when I try to install marsyas on Debian 8 with MATE 1.8.1:
> CMake initialized in the wrong directory.  Please initialize CMake with the top-level Marsyas directory as source directory.

I followed instructions from here: 
[http://marsyasweb.appspot.com/assets/docs/manual/marsyas-user/Configuring-with-CMake.html#Configuring-with-CMake](http://marsyasweb.appspot.com/assets/docs/manual/marsyas-user/Configuring-with-CMake.html#Configuring-with-CMake)

**Comment by jleben** [comment]
Those instructions are outdated. Please follow these instructions available on the Marsyas website:
http://marsyas.info/doc/manual/marsyas-user/Step_002dby_002dstep-building-instructions.html#Step_002dby_002dstep-building-instructions

**Comment by ybayle** [comment]
Ok this new installation process is better than the old one, thanks!
Morever, I think you should precise [here](http://marsyas.info/doc/manual/marsyas-user/Building-latest-Marsyas-on-Debian_002fUbuntu.html#Building-latest-Marsyas-on-Debian_002fUbuntu) that you must run 
"sudo" in front of "make install"
