### ISSUE TITLE
Did this project annotate the tempo of dataset SMC ever before? 

### ISSUE THREAD

**Issue by Okuryo-Qqi** [marsyas/marsyas#75]
I didn't found annotated file of dataset SMC in "collections", did this project annotate the tempo of dataset SMC ever before?

**Comment by gperciva** [comment]
Huh, it should be in https://github.com/marsyas/marsyas/tree/master/scripts/large-evaluators/tempo-ground but it's not.  Sorry, I must have forgotten to do `svn add` back in the day?

PR #76 adds them.

**Comment by gperciva** [comment]
I've merged #76.  Thanks for the report!
